[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "Withdraw precompile for EVM pallet."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-evm-precompile-dna"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.1.0"

[dependencies]
# crates
array-bytes    = { version = "1.1.0" }
codec          = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
ethereum-types = { version = "0.11.0", default-features = false }
evm            = { version = "0.24.0", default-features = false, features = ["with-codec"] }
hex            = { version = "0.4.3", default-features = false }
ripemd160      = { version = "0.9.1", default-features = false }
sha3           = { version = "0.9.1", default-features = false }
# hyperspace
hyperspace-evm = { default-features = false, path = "../../../" }
dp-evm       = { default-features = false, path = "../../../../../primitives/evm" }
ethabi       = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "xavier-no-std" }
# substrate
frame-support    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
frame-system     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
pallet-timestamp = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-core          = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-io            = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-runtime       = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-std           = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }

[features]
default = ["std"]

std = [
	"crates-std",
	"hyperspace-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"ethereum-types/std",
	"evm/std",
	"hex/std",
	"ripemd160/std",
	"sha3/std",
]

hyperspace-std = [
	"hyperspace-evm/std",
	"dp-evm/std",
	"ethabi/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
