[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "FRAME pallet to back Ethereum assets"
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-ethereum-backing"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.2.0"

[dependencies]
# crates
array-bytes = { version = "1.1.0" }
codec       = { package = "parity-scale-codec", version = "2.0.1", default-features = false, features = ["derive"] }
log         = { version = "0.4.14" }
serde       = { version = "1.0.125", optional = true }
serde_json  = { version = "1.0.64", optional = true }
# hyperspace
hyperspace-relay-primitives = { default-features = false, path = "../../../../primitives/relay" }
hyperspace-support          = { default-features = false, path = "../../../support" }
ethabi                    = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "xavier-no-std" }
ethereum-primitives       = { default-features = false, path = "../../../../primitives/ethereum-primitives" }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-io         = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-std        = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[dev-dependencies]
# hyperspace
hyperspace-balances              = { path = "../../../../frame/balances" }
hyperspace-ethereum-linear-relay = { path = "../linear-relay" }
hyperspace-ethereum-relay        = { features = ["deserialize"], path = "../relay" }
hyperspace-relay-primitives      = { path = "../../../../primitives/relay" }
hyperspace-relayer-game          = { path = "../../relayer-game" }
hyperspace-staking               = { path = "../../../../frame/staking" }
ethereum-primitives            = { features = ["deserialize"], path = "../../../../primitives/ethereum-primitives" }
# github
rlp = { version = "0.5.0" }
# substrate
frame-election-provider-support = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
pallet-session                  = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
pallet-timestamp                = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-core                         = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-staking                      = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }

[features]
default = ["std"]

std = [
	"crates-std",
	"hyperspace-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"serde",
	"serde_json",
]
hyperspace-std  = [
	"hyperspace-relay-primitives/std",
	"hyperspace-support/std",
	"ethabi/std",
	"ethereum-primitives/std",
]
substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]

try-runtime = [
	"frame-support/try-runtime",
]
