[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "Runtime primitives for Ethereum RPC (web3) compatibility layer for Hyperspace."
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "dvm-rpc-core"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.1.0"

[dependencies]
# crates
codec          = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
ethereum       = { version = "0.7.1", default-features = false, features = ["with-codec"] }
ethereum-types = { version = "0.11.0", default-features = false }
jsonrpc-core   = { version = "15.1.0" }
jsonrpc-derive = { version = "15.1.0" }
jsonrpc-pubsub = { version = "15.1.0" }

# hyperspace
hyperspace-evm    = { default-features = false, path = "../../evm" }
dp-evm          = { default-features = false, path = "../../../primitives/evm" }
dp-rpc          = { default-features = false, path = "../../../primitives/rpc" }
# substrate
sp-api     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-core    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-runtime = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }
sp-std     = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "rococo-v1.1" }

[features]
default = ["std"]

std = [
	"crates-std",
	"hyperspace-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"ethereum/std",
	"ethereum-types/std",
]
hyperspace-std  = [
	"hyperspace-evm/std",
	"dp-evm/std",
]
substrate-std = [
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
]
