[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "FRAME pallet to back Ethereum assets"
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-ethereum-issuing-contract"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.2.0"

[dependencies]
# crates
ethereum-types = { default-features = false, version = "0.11.0" }
# github
ethabi = { default-features = false, git = "https://github.com/darwinia-network/ethabi.git", branch = "xavier-no-std" }

[features]
default = ["std"]

std = [
	"crates-std",
	"github-std",
]

crates-std = [
	"ethereum-types/std",
]
github-std = [
	"ethabi/std",
]
