[package]
authors     = ["Hyperspace Network <contact@mvs.org>"]
description = "FRAME to issue CETP"
edition     = "2018"
homepage    = "https://mvs.org/"
license     = "GPL-3.0"
name        = "hyperspace-oldetp-issuing"
readme      = "README.md"
repository  = "https://github.com/mvs-org/Hyperspace"
version     = "2.2.0"

[dependencies]
# crates
codec      = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
log        = { version = "0.4.14", optional = true }
paste      = { version = "1.0.5", optional = true }
serde      = { version = "1.0.125", optional = true }
serde_json = { version = "1.0.64", optional = true }
# substrate
frame-support = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
frame-system  = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
sp-runtime    = { default-features = false, git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
# hyperspace
hyperspace-support = { optional = true, path = "../../../support" }

[dev-dependencies]
# substrate
sp-io = { git = "https://github.com/darwinia-network/substrate.git", tag = "darwinia-v0.10.0" }
# hyperspace
hyperspace-balances = { path = "../../../balances" }
hyperspace-support  = { path = "../../../support" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std    = [
	"codec/std",
	"serde/std",
]
substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"sp-runtime/std",
]

genesis-loader = [
	"serde_json",
	"hyperspace-support",
]

try-runtime = [
	"log",
	"paste",
	"frame-support/try-runtime",
]
